server:
  port: 9301

spring:
  application:
    name: spring-cloud-admin

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/