server:
  port: 8301

spring:
  application:
    name: spring-cloud-ribbon

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/

service-url:
   user-service: http://spring-cloud-producer
