server:
  port: 8901

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          # 配置存储配置信息的Git仓库
          uri: https://gitee.com/Purezento/spring-cloud-config.git
          username: silencetea
          password: Xx15859535599
          # 开启启动时直接从git获取配置
          clone-on-start: true
          # 获取子目录下的配置
#          search-paths: '{application}'
  # rabbitmq相干配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

# 暴露bus刷新配置的端点
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://root:root@localhost:8761/eureka/